services:
  ios-backup:
    build:
      context: .
    image: ios-backup:1.0
    container_name: iOSBackup
    restart: always
    privileged: true
    network_mode: host
    volumes:
      - /mnt/HDD/iOS/:/iPhone
      - ./app:/app
    environment:
      - PORT=89
      - BASE_URL=/api/ingress/backup
networks: {}
