services:
  ios-backup:
    image: ios-backup:1.0
    build:
      context: .
    container_name: iOSBackup
    restart: always
    privileged: true
#    network_mode: host
    volumes:
      - /mnt/HDD/iOS/:/iPhone
      - ./app:/app
    environment:
      - PORT=3000
      - BASE_URL=/api/ingress/backup
networks:
  default:
    name: nginx_default
    external: true          
